checking of constant/writable arguments
jasmin-lang/jasmin pull request #178
Opened 2022-06-22 13:40 UTC by bgregoir

2022-06-22 14:32 UTC, vbgl commented on compiler/src/pretyping.ml
> +(*    reject_constant_pointers loc x ; *)
Maybe this line should be removed completely.

2022-06-22 14:54 UTC, eponier commented
This example is artificial, but do we want to accept such things?

```
fn f (reg ptr u64[1] r) -> reg u64 {
  reg u64 res;
  stack u64[1] s;

  r = s;
  r[0] = 1;
  res = r[0];

  return res;
}

export fn main () -> reg u64 {
  reg u64 res;
  stack u64[1] s;

  s[0] = 1;

  res = f(s);

  return res;
}
```

2022-06-22 14:58 UTC, vbgl requested changes
This is not ready. The following program is now rejected:

~~~
fn zerofill(reg mut ptr u64[1] x) -> reg ptr u64[1] {
  x[0] = 0;
  return x;
}

export
fn main() -> reg u64 {
  stack u64[1] s;
  s = zerofill(s);
  reg u64 r;
  r = s[0];
  return r;
}
~~~

2022-06-22 15:23 UTC, eponier commented
With @bgregoir, we are not sure what to do exactly, so let's postpone this a bit.

2022-06-22 15:38 UTC, vbgl commented
IMHO, it is OK to reject the artificial example above.

2022-06-23 07:16 UTC, bgregoir commented
I did not see your last commit and I did the same patch. 
Anyway I think we try to ensure something that is verified later by the compiler without having all the information.
We can do a variation of zerofill example:

inline fn zerofill(stack u64[1] x) -> stack u64[1] {
  x[0] = 0;
  return x;
}

export
fn main() -> reg u64 {
  stack u64[1] s;
  reg const ptr u64[1] t;
  t = s;
  s = zerofill(t);
  reg u64 r;
  r = s[0];
  return r;
}

2022-06-23 20:12 UTC, vbgl commented on compiler/src/pretyping.ml
> +  | Export -> if is_inline = E.InlineFun then rs_tyerror ~loc (string_error "call to export function needs to be inlined")
This test is wrong…

2022-06-23 20:20 UTC, vbgl commented on compiler/src/pretyping.ml
> +  | Export -> if is_inline = E.InlineFun then rs_tyerror ~loc (string_error "call to export function needs to be inlined")
Fixed!

2022-06-24 04:49 UTC, vbgl commented
Unless someone wants to implement a more precise check, I recommend to merge this PR as is.

2022-06-24 08:23 UTC, bgregoir commented
Ok with this.

2022-06-24 08:25 UTC, bgregoir commented
Apparently I can't merge it myself.

2022-06-24 08:28 UTC, eponier commented
You have to accept it first (i.e. add a positive review).

2022-06-24 08:38 UTC, eponier approved these changes
@bgregoir accepts his own PR

2022-06-24 08:38 UTC, merged