Arm instructions for long multiplication
jasmin-lang/jasmin pull request #481
Opened 2023-06-16 12:24 UTC by Slukoo

Added UMLAL, SMULL, SMLAL, SMMUL & SMMULR instructions.

2023-06-16 13:25 UTC, bgregoir requested changes
I thank a lot for this PR. 
I have a small general remark:
    it seems that you frequently use the same sequence of code:
       let lo := zero_extend U32 res in
       let hi := zero_extend U32 (wshr res 32) in
    Can you introduce some intermediate function to do that (in word.v)
    Maybe it can be implemented using other pattern (split_word? I do not remember the name). 

A more problematic remark:

I think that the semantic of the instructions are wrong.
Most of then should compute (x * y + (u : v))
The general pattern you use in
    (l,h) = x * y 
    (u+l, h + v)
I think this is incorrect because the carry that can occurs in u + l is not propagated to the high part.

2023-06-16 13:25 UTC, bgregoir commented on proofs/compiler/arm_instr_decl.v
> +  let res := (zero_extend U64 wn * zero_extend U64 wm)%R in
I think the EC code is much simpler and 
it a more direct translation of the spec.
Can we wrote it in this style ?

2023-06-16 13:25 UTC, bgregoir commented on proofs/compiler/arm_instr_decl.v
> +  let lo := sign_extend U32 res in
same remark here, maybe the write way to do it
is to add an operator in word.v of type 
    word s -> word s -> word s * word s.
Maybe it already exists.

2023-06-16 13:25 UTC, bgregoir commented on proofs/compiler/arm_instr_decl.v
> +  let res := (sign_extend U64 wn * sign_extend U64 wm)%R in
same remark

2023-06-16 20:16 UTC, Slukoo commented
Thank you for your remarks ! I’ll try to correct my mistakes as soon as I can.

De : ***@***.***>
Envoyé le :vendredi 16 juin 2023 15:26
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [jasmin-lang/jasmin] Arm instructions for long multiplication (PR #481)


@bgregoir requested changes on this pull request.

I thank a lot for this PR.
I have a small general remark:
it seems that you frequently use the same sequence of code:
let lo := zero_extend U32 res in
let hi := zero_extend U32 (wshr res 32) in
Can you introduce some intermediate function to do that (in word.v)
Maybe it can be implemented using other pattern (split_word? I do not remember the name).

A more problematic remark:

I think that the semantic of the instructions are wrong.
Most of then should compute (x * y + (u : v))
The general pattern you use in
(l,h) = x * y
(u+l, h + v)
I think this is incorrect because the carry that can occurs in u + l is not propagated to the high part.


In eclib/JModel_m4.ec<https://github.com/jasmin-lang/jasmin/pull/481#discussion_r1232220911>:

> +op SMULLcc x y g o h = if g then SMULL x y else (o, h).

+

+op SMLAL (u v x y: W32.t) : W32.t * W32.t =

+  let lo = x * y in

+  let hi = wmulhs x y in

+  (lo + u, hi + v).

+op SMLALcc u v x y g o h= if g then SMLAL u v x y else (o, h).

+

+op SMMUL (x y: W32.t) : W32.t =

+  wmulhs x y.

+op SMMULcc x y g o = if g then SMMUL x y else o.

+

+op SMMULR (x y: W32.t) : W32.t =

+  let lo = x * y in

+  let hi = wmulhs x y in

+  if 2147483648 <= to_uint lo

Can you at least add a comment saying that 2147483648 is 2^31.
It seems to come from nowhere :-)


In proofs/compiler/arm_instr_decl.v<https://github.com/jasmin-lang/jasmin/pull/481#discussion_r1232228021>:

> @@ -829,6 +841,135 @@ Definition arm_UMULL_instr : instr_desc_t :=

     id_pp_asm := pp_arm_op mn opts;

   |}.



+Definition arm_UMLAL_semi (dlo dhi wn wm : ty_r) : exec ty_rr :=

+  let res := (zero_extend U64 wn * zero_extend U64 wm)%R in

I think the EC code is much simpler and
it a more direct translation of the spec.
Can we wrote it in this style ?


In proofs/compiler/arm_instr_decl.v<https://github.com/jasmin-lang/jasmin/pull/481#discussion_r1232233543>:

> +    id_out := [:: E 0; E 1 ];

+    id_semi := arm_UMLAL_semi;

+    id_nargs := 4;

+    id_args_kinds := ak_reg_reg_reg_reg;

+    id_eq_size := refl_equal;

+    id_tin_narr := refl_equal;

+    id_tout_narr := refl_equal;

+    id_check_dest := refl_equal;

+    id_str_jas := pp_s (string_of_arm_mnemonic mn);

+    id_safe := [::]; (* TODO_ARM: Complete. *)

+    id_pp_asm := pp_arm_op mn opts;

+  |}.

+

+Definition arm_SMULL_semi (wn wm : ty_r) : exec ty_rr :=

+  let res := (sign_extend U64 wn * sign_extend U64 wm)%R in

+  let lo := sign_extend U32 res in

same remark here, maybe the write way to do it
is to add an operator in word.v of type
word s -> word s -> word s * word s.
Maybe it already exists.


In proofs/compiler/arm_instr_decl.v<https://github.com/jasmin-lang/jasmin/pull/481#discussion_r1232236254>:

> +    id_tout := [:: sreg; sreg ];

+    id_out := [:: E 0; E 1 ];

+    id_semi := arm_SMULL_semi;

+    id_nargs := 4;

+    id_args_kinds := ak_reg_reg_reg_reg;

+    id_eq_size := refl_equal;

+    id_tin_narr := refl_equal;

+    id_tout_narr := refl_equal;

+    id_check_dest := refl_equal;

+    id_str_jas := pp_s (string_of_arm_mnemonic mn);

+    id_safe := [::]; (* TODO_ARM: Complete. *)

+    id_pp_asm := pp_arm_op mn opts;

+  |}.

+

+Definition arm_SMLAL_semi (dlo dhi wn wm : ty_r) : exec ty_rr :=

+  let res := (sign_extend U64 wn * sign_extend U64 wm)%R in

same remark

—
Reply to this email directly, view it on GitHub<https://github.com/jasmin-lang/jasmin/pull/481#pullrequestreview-1483457912>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZZZAM34TG7Q4QKLN4FPLL3XLRNHHANCNFSM6AAAAAAZJF5RZU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-16 20:16 UTC, Slukoo commented on proofs/compiler/arm_instr_decl.v
> +  ok (sign_extend U32 (wshr res 32)).
Thank you for your remarks ! I’ll try to correct my mistakes as soon as I can.

2023-06-19 13:57 UTC, Slukoo commented
Thank you for your help, I tried addressing the issues you were pointing out. Please tell me if there are still some things to improve/correct

2023-06-21 06:16 UTC, bgregoir approved these changes
thank for all the changes. I think it is ok now.

2023-06-21 06:19 UTC, merged