Risc v constants if while
jasmin-lang/jasmin pull request #934
Opened 2024-10-18 07:53 UTC by bgregoir

2024-10-21 08:43 UTC, eponier requested changes
I have a few minor comments.

Another question is whether the name of the pass "prelowering" is a good one. Maybe we should just call it "load constants in cond" with a comment explaining it is called only on RISC-V?

2024-10-21 08:43 UTC, eponier commented on compiler/src/glob_options.ml
> +  | Compiler.PreLowering                 -> "prelowerign", "arch-specific transformations before lowering"
```suggestion
  | Compiler.PreLowering                 -> "prelowering", "arch-specific transformations before lowering"
```

2024-10-21 08:43 UTC, eponier commented on compiler/tests/fail/warning/load_constant_warning.jazz
> +}
I would move the file to a new subdir `risc-v`, because it is only on this arch that there is a warning.

2024-10-21 08:43 UTC, eponier commented on proofs/compiler/arch_params.v
> +Require Import Uint63.
```suggestion
```
We don't need that line anymore.

2024-10-21 08:43 UTC, eponier commented on proofs/compiler/arm_params_proof.v
> -
Please don't remove lines for no reason.

2024-10-21 08:43 UTC, eponier commented on proofs/compiler/riscv_params.v
> -
Idem, don't remove this line. It is on purpose that we have two blank lines here.

2024-10-21 08:43 UTC, eponier commented on proofs/compiler/riscv_params_proof.v
> -
Idem.

2024-10-21 08:43 UTC, eponier commented on proofs/compiler/load_constants_in_cond_proof.v
> +Local Lemma Hsyscall : sem_Ind_syscall p Pi_r.
I'm picky, but please move this lemma between `Hopn` and `Hif_true`.

2024-10-21 08:43 UTC, eponier commented on proofs/compiler/load_constants_in_cond_proof.v
> +(* FIXME move this lemma also in makereference_argument_proof *)
Please fix this FIXME before we merge.

2024-10-23 13:48 UTC, bgregoir commented on proofs/compiler/load_constants_in_cond_proof.v
> +Local Lemma Hsyscall : sem_Ind_syscall p Pi_r.
done.

2024-10-23 13:53 UTC, bgregoir commented on proofs/compiler/arm_params_proof.v
> -
Done, but we lost our time with this.

2024-10-23 13:54 UTC, bgregoir commented on proofs/compiler/load_constants_in_cond_proof.v
> +(* FIXME move this lemma also in makereference_argument_proof *)
This is indeed important

2024-10-23 14:03 UTC, bgregoir commented on proofs/compiler/arch_params.v
> +Require Import Uint63.
It is needed line 25.

2024-10-23 14:07 UTC, bgregoir commented on proofs/compiler/load_constants_in_cond_proof.v
> +(* FIXME move this lemma also in makereference_argument_proof *)
done

2024-10-23 17:04 UTC, eponier commented
I took the liberty to rename the pass ("prelowering" was unclear). If you agree with the changes I did, I'll merge.

2024-10-23 17:05 UTC, eponier commented
One side note: maybe it would make sense not to print the program after the pass when actually the pass is not called (on x86 and arm), but this is not so clear to me.

2024-11-04 12:20 UTC, clebreto commented
@bgregoir @eponier 

What's the status of this MR ?

2024-11-05 07:02 UTC, bgregoir commented
For me it is ok, we can merge it.
I agree that the printing can be removed is the pass is not used (but it is not important).

2024-11-05 09:22 UTC, eponier commented
Ok, I'm merging then.

2024-11-05 09:26 UTC, merged