Modified toCL to be able to run reduce4 mulx example and added the reduce4 mulx example
jasmin-lang/jasmin pull request #946
Opened 2024-10-29 10:15 UTC by JoaoDiogoDuarte

Depends on https://github.com/jasmin-lang/jasmin/pull/944 and https://github.com/jasmin-lang/jasmin/pull/945.

This merge request adds:
- reduce4.jazz example with abstract predicates and asserts/assumes that will result in a valid and correct cryptoline file

And adds the following translations:
- ADOX
- ADCX
- MULX

and changes the IMULr translation to include an assert.

2024-12-17 17:10 UTC, lyonel2017 commented
@JoaoDiogoDuarte can you address my previous remarks.

2024-12-17 17:15 UTC, JoaoDiogoDuarte commented
> @JoaoDiogoDuarte can you address my previous remarks.

I'd be happy to, but I don't see any on any remarks in any of the pull requests concerning cryptoline. Do you mind writing them down please? Apologies if you already said them in one of our meetings.

2024-12-17 21:13 UTC, lyonel2017 requested changes

2024-12-19 15:24 UTC, lyonel2017 approved these changes

2024-12-19 15:26 UTC, merged