use byte array in extraction
jasmin-lang/jasmin pull request #995
Opened 2024-12-15 05:04 UTC by bgregoir

use byte array in extraction

2024-12-20 15:38 UTC, cassiersg requested changes
Looks overall good to me (& very tidy !).

2024-12-20 17:22 UTC, bgregoir commented on compiler/tests/success/x86-64/array_cast.ec
Thank for all the comment, I will try to finish this properly

2024-12-21 13:29 UTC, bgregoir commented on compiler/entry/jasmin2ec.ml
> +     (Deprecate) $(b,old): old representation for array operations (anonymous functions instead of eclib functions)."
done

2024-12-21 13:32 UTC, bgregoir commented on compiler/entry/jasmin2ec.ml
> +  Arg.(value & opt (Arg.enum alts) ToEC.BArray & info ["am"; "array-model"] ~doc)
I have follow the same pattern than the option "oa" and "output-array". But I don't care, we can keep only --array-model.

2024-12-21 13:32 UTC, bgregoir commented on compiler/tests/success/x86-64/array_cast.ec
done

2024-12-21 14:51 UTC, bgregoir commented on compiler/entry/jasmin2ec.ml
> +  Arg.(value & opt (Arg.enum alts) ToEC.BArray & info ["am"; "array-model"] ~doc)
done

2024-12-23 12:13 UTC, cassiersg commented on compiler/entry/jasmin2ec.ml
> +  Arg.(value & opt (Arg.enum alts) ToEC.BArray & info ["am"; "array-model"] ~doc)
Yes, `--oa` was a bad idea.

2024-12-23 12:16 UTC, cassiersg approved these changes

2025-01-16 17:20 UTC, vbgl approved these changes

2025-01-16 20:06 UTC, vbgl approved these changes

2025-01-16 20:06 UTC, merged